apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend-master
  labels:
    app: chat
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: eftech93/chat-backend:latest
        env:
        - name: PORT
          value: "3400"
        - name: RABBIT_MQ_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: chat-configs
              key: broker_uri
        ports:
        - containerPort: 3400
          name: ws-port
        resources:
          requests: 
            cpu: "250m"
          limits:
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend-master
  labels:
    app: backend
spec:
  type: NodePort
  ports:
  - port: 3400
    targetPort: ws-port
  selector:
    app: backend


